/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package associations;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AssociationsTest {
  @Test void customerTest(){
    // Instantiate a customer
    Customer c1 = new Customer("Early", "James", "123 Main St", "13126");
    assertEquals("Early", c1.getLastName(), "\n\tExpected: Early\n\t  Actual: " + c1.getLastName() );
    assertEquals("James", c1.getFirstName(), "\n\tExpected: James\n\t  Actual: " + c1.getFirstName() );
    assertEquals("123 Main St", c1.getStreetAddress(), "\n\tExpected: 123 Main St\n\t  Actual: " + c1.getStreetAddress() );
    assertEquals("13126", c1.getZipCode(), "\n\tExpected: 13126\n\t  Actual: " + c1.getZipCode() );
    assertNull(c1.getAccount(), "Initial Account reference should be null");
  }

  @Test void accountTest(){
    // Instantiate a customer
    Customer c1 = new Customer("Early", "James", "123 Main St", "13126");

    // Create an account
    Account a1 = new Account("123-456-78", c1);
    assertEquals("123-456-78", a1.getAccountNumber());
    assertEquals(c1, a1.getCustomer());
    assertEquals(a1.getBalance(), 0);

    // Associate account with customer
    c1.setAccount(a1);
    assertEquals(a1, c1.getAccount());
  }

  @Test void productTest(){
    // Instantiate a product
    Product p1 = new Product("Snickers", "234-567-89", 0.99);
    assertEquals("Snickers", p1.getProductName());
    assertEquals("234-567-89", p1.getIsbn());
    assertEquals(0.99, p1.getUnitPrice());
  }

  @Test void orderItemTest(){
    // Instantiate a product
    Product p1 = new Product("Snickers", "234-567-89", 0.99);

    // Instantiate an OrderItem
    OrderItem oi1 = new OrderItem(p1, 2);

    assertEquals(p1, oi1.getProduct());
    assertEquals(2, oi1.getQuantity());
    assertEquals(1.98, oi1.getPrice());
  }

  @Test void orderTest(){
    // Instantiate a customer
    Customer c1 = new Customer("Early", "James", "123 Main St", "13126");
    // Create an account
    Account a1 = new Account("123-456-78", c1);
    // Associate with customer
    c1.setAccount(a1);

    // Instantiate some products
    Product p1 = new Product("Snickers", "234-567-89", 0.99);
    Product p2 = new Product("Ear buds", "345-678-90", 10.99);
    Product p3 = new Product("Socks", "345-678-90", 4.99);


    // Instantiate OrderItems
    OrderItem oi1 = new OrderItem(p1, 2);
    OrderItem oi2 = new OrderItem(p2, 1);
    OrderItem oi3 = new OrderItem(p3, 3);

    // Instantiate an Order
    Order o1 = new Order(a1);
    assertEquals(a1, o1.getAccount());
    assertEquals(0, o1.getItems().length); // Should be an array of length 0

    // Add items to the order
    o1.addItem(oi1);
    o1.addItem(oi2);
    o1.addItem(oi3);
    // Check the size and total price
    assertEquals(3, o1.getItems().length);
    assertEquals(27.94, o1.getTotal());
  }


}
