/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package associations;

public class Customer {

  // Add instance varables

  //    A constructor that initializes the last name, first name, address, and zip code.

  //    getLastName() - Returns a String that is the customer’s last name

  //    getFirstName() - Returns a String that is the customer’s first name

  //    getStreetAddress() - Returns a String indicating the customer’s street address

  //    getZipCode() - Returns a String indicating the customer’s zip code

  //    setAccount(Account a) - Sets the Account for this customer

  //    getAccount() - Returns a reference to the Account object associated with this customer

}
